spring: 
  application:
    name: infuse-test-api
  datasource:
    url: jdbc:mariadb://localhost:3307/infuse-test?createDatabaseIfNotExist=true
    username: root
    password: 1q2w3e
    driver-class-name: org.mariadb.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    generate-ddl: true
    hibernate: 
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true